### ISSUE TITLE
Create DB MongoDB

### ISSUE THREAD

**Issue by membriux** [Albertwo512/X-B2#1]
- [x] Create Mongo DB using [Back4app.com](https://www.back4app.com/)

**Comment by Albertwo512** [comment]
i create a db in [Back4app.com](https://www.back4app.com/)
<img width="1679" alt="Captura de pantalla 2024-05-15 a la(s) 13 10 30" src="https://github.com/Albertwo512/X-B2/assets/122117432/c8ee365c-a74b-4ae1-9033-079ce947846b">

**Comment by membriux** [comment]
Looks great! Feel free to to close this issue to mark it as complete

**Comment by Albertwo512** [comment]
Thank you, have a good day
