### ISSUE TITLE
Design Basic Web App flow

### ISSUE THREAD

**Issue by membriux** [Albertwo512/X-B2#3]
- [ ] Initial Figma design of webapp
- [ ] Add design screenshots to README.md
  - [ ] Add simple explanations/descriptions of the design in the readme.md

**Comment by Albertwo512** [comment]
I'm still working on the design, but before that i want to show you some of the job.

<img width="1037" alt="Captura de pantalla 2024-05-20 a la(s) 13 27 43" src="https://github.com/Albertwo512/X-B2/assets/122117432/c6e953bc-568b-437c-8364-70ab6cc01f46">

<img width="1040" alt="Captura de pantalla 2024-05-20 a la(s) 13 27 06" src="https://github.com/Albertwo512/X-B2/assets/122117432/eb03bf75-0846-4ce0-bec3-ae032ad1238c">
