### ISSUE TITLE
Connect React App to Mongo DB

### ISSUE THREAD

**Issue by membriux** [Albertwo512/X-B2#4]
- [ ] Go over Back4app documentation to learn how to connect React App -> MongoDB
  - Documentation -> https://www.back4app.com/docs/react/quickstart
- [ ] React app is able to create object in database

**Comment by Albertwo512** [comment]
ready
<img width="1678" alt="Captura de pantalla 2024-05-21 a la(s) 13 54 46" src="https://github.com/Albertwo512/X-B2/assets/122117432/267acec4-745d-4a0a-8dad-0f5d6254727e">
<img width="1680" alt="Captura de pantalla 2024-05-21 a la(s) 13 55 00" src="https://github.com/Albertwo512/X-B2/assets/122117432/75d3e945-08f7-4d1f-9bea-b48537e08c3c">

**Comment by membriux** [comment]
Looks great! Lets move on to adding signup/login logic to your app.
