### ISSUE TITLE
React - Login / Signup Page

### ISSUE THREAD

**Issue by membriux** [Albertwo512/X-B2#7]
Note: You must finish learning how to connect react app to database

Functionality
- [x] Use back4app documentation to learn how to add Login/Sign up from react app
  - [x] https://www.back4app.com/docs/react/working-with-users/sign-up-page-react
- [x] Customize signup/login page
- [x] Add error validation 
  - [x] example: tell user that wrong password

Demo: 
- [x] GIF showing user sign up successful
- [x] GIF showing user login success
- [x] GIF showing login WRONG password error to user

**Comment by Albertwo512** [comment]
Here is the video demo, is on Google drive because is too heavy
https://drive.google.com/file/d/1m5Hdb8SaXbFmoqCohOg_T9kJyqrCA0oe/view?usp=drive_link
let me know if you need anything else

**Comment by membriux** [comment]
This looks great!
Can you also post a screenshot of your database showing the user after it was created successfully?

Additionally, please use Licecap to record GIFs so you can have them in your descriptions and not deal with Google Drive links: https://www.cockos.com/licecap/

^^^ Please add all this to your Pull Request description
