### ISSUE TITLE
React Router for login

### ISSUE THREAD

**Issue by membriux** [Albertwo512/X-B2#8]
Learn how to implement ROUTES in react.

- [x] Implement Authentication + Protected React Routes
  - [x] Example: https://v5.reactrouter.com/web/example/auth-workflow
- [x] User should go to login page if not Authenticated

**Comment by Albertwo512** [comment]
It's ready, check and tell me what you think...
![Test1](https://github.com/Albertwo512/X-B2/assets/122117432/857ce381-202e-4597-8891-6bf076e3a401)

**Comment by membriux** [comment]
@Albertwo512  Looks perfect, please add the GIF to the Pull Request Description
